name: Hello-World

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello build
        run: echo "Hello, ${{ vars.STAGE1 }}"
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Hello build
        run: echo "Hello, ${{ vars.STAGE2 }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Hello build
        run: echo "Hello, ${{ vars.STAGE3 }}",${{ secrets.DOCKERPASSWORD}}"
     
